"""Add username and bio to platform_users

Revision ID: 3aa4f5c402ac
Revises: 0001
Create Date: 2025-09-27 14:14:12.951352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aa4f5c402ac'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('club_members_club_id_email_key'), 'club_members', type_='unique')
    op.drop_index(op.f('ix_club_members_club_id'), table_name='club_members')
    op.add_column('club_roles', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('club_roles_club_id_user_id_key'), 'club_roles', type_='unique')
    op.drop_index(op.f('ix_club_roles_club_id'), table_name='club_roles')
    op.drop_index(op.f('ix_clubs_slug'), table_name='clubs')
    op.drop_index(op.f('ix_membership_tiers_club_id'), table_name='membership_tiers')
    op.drop_constraint(op.f('membership_tiers_club_id_slug_key'), 'membership_tiers', type_='unique')
    op.drop_column('platform_subscriptions', 'stripe_price_id')
    op.add_column('platform_users', sa.Column('username', sa.String(length=50), nullable=False))
    op.add_column('platform_users', sa.Column('bio', sa.String(length=500), nullable=True))
    op.drop_index(op.f('ix_platform_users_email'), table_name='platform_users')
    op.create_unique_constraint(None, 'platform_users', ['username'])
    op.drop_column('platform_users', 'stripe_customer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_users', sa.Column('stripe_customer_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'platform_users', type_='unique')
    op.create_index(op.f('ix_platform_users_email'), 'platform_users', ['email'], unique=True)
    op.drop_column('platform_users', 'bio')
    op.drop_column('platform_users', 'username')
    op.add_column('platform_subscriptions', sa.Column('stripe_price_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('membership_tiers_club_id_slug_key'), 'membership_tiers', ['club_id', 'slug'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_membership_tiers_club_id'), 'membership_tiers', ['club_id'], unique=False)
    op.create_index(op.f('ix_clubs_slug'), 'clubs', ['slug'], unique=True)
    op.create_index(op.f('ix_club_roles_club_id'), 'club_roles', ['club_id'], unique=False)
    op.create_unique_constraint(op.f('club_roles_club_id_user_id_key'), 'club_roles', ['club_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('club_roles', 'updated_at')
    op.create_index(op.f('ix_club_members_club_id'), 'club_members', ['club_id'], unique=False)
    op.create_unique_constraint(op.f('club_members_club_id_email_key'), 'club_members', ['club_id', 'email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
